config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  # allows @restaurant.reviews
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  # allows review.restaurant
  validates :rating, presence: true, numericality: { only_integer: true, in: 0..5 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(strong_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def strong_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(strong_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def strong_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name  %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p>
  <%= @restaurant.address %> <br>
  <%= @restaurant.phone_number %> <br>
  <%= @restaurant.category %>
</p>

<h2>Reviews</h2>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %>, <%= review.rating %></li>
  <% end %>
</ul>
<br>
<%= link_to "Add a review", new_restaurant_review_path(@restaurant)%>
<br>
<%= link_to "Back to restaurants", restaurants_index_path%>

</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content  %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>